brew 'asdf'
brew 'uv'
brew 'llm'
brew 'bat'
brew 'glow'
brew 'gh'
brew 'yt-dlp'
brew 'rg'
brew 'localtunnel'
brew 'htop'
brew 'watchman'
brew 'fastfetch'
brew 'ffmpeg'

# DB
tap 'mongodb/brew'
brew 'mongodb-database-tools'
cask 'mongodb-compass'

# CLI Agents
brew 'codex'
brew 'sst/tap/opencode'
cask 'repo-prompt'
tap 'steipete/tap'
brew 'peekaboo'

# Apps
cask 'slack'
cask 'google-chrome'
cask 'rectangle'
cask 'warp'
cask 'docker-desktop'
cask 'visual-studio-code@insiders'
cask 'google-drive'
cask 'google-cloud-sdk'
cask 'Raycast'
cask 'brave-browser'
cask 'expo-orbit'
cask 'microsoft-edge'
cask 'figma'
cask 'enpass'
cask 'claude'
cask 'lm-studio'
cask 'android-studio'
cask 'zulu@17'
cask 'vlc'
cask 'gimp'
cask 'blender'
