tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'caskroom/cask'
tap 'caskroom/versions'

cask 'java'
cask 'java7'

brew 'asciidoc'
brew 'cheat'
brew 'cloc'
brew 'cmake'
brew 'ctags'
brew 'diff-so-fancy'
brew 'git-extras'
brew 'homebrew/dupes/ncurses'
brew 'htop'
brew 'readline'
brew 'sqlite'
brew 'python3'
brew 'httpie'
brew 'imagemagick'
brew 'jenv'
brew 'jq'
brew 'lua'
brew 'python'
brew 'macvim', args: ['with-lua']
brew 'maven'
brew 'mongodb'
brew 'nvm'
brew 'pandoc'
brew 'reattach-to-user-namespace'
brew 'rename'
brew 'sbt'
brew 'the_silver_searcher'
brew 'tidy-html5'
brew 'tmux'
brew 'watchman'
brew 'wget'
brew 'youtube-dl'
brew 'homebrew/versions/node4-lts'
brew 'tree'
brew 'gradle'

cask 'betterzipql'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'aerial'
cask 'alfred'
cask 'evernote'
cask 'google-chrome'
cask 'iterm2'
cask 'mattermost'
cask 'virtualbox'
cask 'vlc'
cask 'spectacle'

